programs:
  nginx:
    cmd: "sleep 10"
    numprocs: 6
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes:
      - 0
      - 2
    startretries: 2
    starttime: 5
    stopsignal: SIGTERM
    stoptime: 10
    env:
      STARTED_BY: taskmaster
      ANSWER: '42'
  vogsphere:
    cmd: "sleep 2"
    numprocs: 1
    umask: 077
    workingdir: /tmp
    autostart: false
    autorestart: unexpected
    exitcodes: 
      - 0
    startretries: 0
    starttime: 3
    stopsignal: USR1
    stoptime: 10
    stdout: /tmp/vgsworker.stdout
    stderr: /tmp/vgsworker.stderr